### ISSUE TITLE
新版设置页的一堆哦买噶问题

### ISSUE THREAD

**Issue by AGJ-smart** [Sharll-large/FMCL#11]
**Describe the bug**
.minecraft Path的browse有问题：
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\15071\Desktop\programme\FMCL's stuff\FMCL-main\FMCLView\pages\settings.py", line 37, in save
    config.change_config_and_safe(dir)
TypeError: Config.change_config_and_safe() missing 1 required positional argument: 'value'
```
save按钮也有问题
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\15071\Desktop\programme\FMCL's stuff\FMCL-main\FMCLView\pages\settings.py", line 131, in del_account
    select = account_list.curselection()[0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\15071\Desktop\programme\FMCL's stuff\FMCL-main\FMCLView\pages\settings.py", line 37, in save
    config.change_config_and_safe(dir)
TypeError: Config.change_config_and_safe() missing 1 required positional argument: 'value'
```
启动按钮没有翻译

新增微软账户弹出浏览器之后切回FMCL主程序回调链接输入框不会置于上层 我找了三回啊三回才找到

**FMCL logs**
没有！

**Other launcher's launch script**
没有！

**Comment by AGJ-smart** [comment]
启动选项卡按钮没翻译修完了

**Comment by pxinz** [comment]
问题解决了我close了（
