### ISSUE TITLE
启动 FMCL Preview 10 出错

### ISSUE THREAD

**Issue by AGJ-smart** [Sharll-large/FMCL#13]
### Describe the bug
系统：Windows 11

行为：使用终端执行 `python.exe FMCL.pyzw` 后报错。

控制台信息：

PS D:\Minecraft> python.exe .\FMCL.pyzw
Traceback (most recent call last):
  File "D:\Minecraft\FMCL.pyzw\__main__.py", line 59, in <module>
    main(*sys.argv)
  File "D:\Minecraft\FMCL.pyzw\__main__.py", line 53, in main
    FMCLView.main.main()
  File "D:\Minecraft\FMCL.pyzw\FMCLView\main.py", line 31, in main
    gui.page_func("launch")(launch.page)
  File "D:\Minecraft\FMCL.pyzw\FMCLView\tk_extend\frame.py", line 18, in <lambda>
    return lambda p_func: self.page(name, p_func(self))
                                          ^^^^^^^^^^^^
  File "D:\Minecraft\FMCL.pyzw\FMCLView\pages\launch.py", line 118, in page
    refresh_version_list()
  File "D:\Minecraft\FMCL.pyzw\FMCLView\pages\launch.py", line 53, in refresh_version_list
    choose_version_comb["values"] = [langs["Launch.GUI.Choose_Version_Comb.Default"]] + versions.local_version(
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Minecraft\FMCL.pyzw\FMCLCore\system\CoreVersionGet.py", line 24, in local_version
    for i in os.listdir(os.path.join(mcpath, "versions")):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '.minecraft\\versions'
ERROR:root:Error happened! Error message:
 Traceback (most recent call last):
  File "D:\Minecraft\FMCL.pyzw\__main__.py", line 59, in <module>
    main(*sys.argv)
  File "D:\Minecraft\FMCL.pyzw\__main__.py", line 53, in main
    FMCLView.main.main()
  File "D:\Minecraft\FMCL.pyzw\FMCLView\main.py", line 31, in main
    gui.page_func("launch")(launch.page)
  File "D:\Minecraft\FMCL.pyzw\FMCLView\tk_extend\frame.py", line 18, in <lambda>
    return lambda p_func: self.page(name, p_func(self))
                                          ^^^^^^^^^^^^
  File "D:\Minecraft\FMCL.pyzw\FMCLView\pages\launch.py", line 118, in page
    refresh_version_list()
  File "D:\Minecraft\FMCL.pyzw\FMCLView\pages\launch.py", line 53, in refresh_version_list
    choose_version_comb["values"] = [langs["Launch.GUI.Choose_Version_Comb.Default"]] + versions.local_version(
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Minecraft\FMCL.pyzw\FMCLCore\system\CoreVersionGet.py", line 24, in local_version
    for i in os.listdir(os.path.join(mcpath, "versions")):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '.minecraft\\versions'

Exception in thread Thread-1 (check):
Traceback (most recent call last):
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Minecraft\FMCL.pyzw\update.py", line 46, in check
  File "D:\Minecraft\FMCL.pyzw\update.py", line 30, in _get_version
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\15071\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

FMCL Error 提示框：
![提示框](https://user-images.githubusercontent.com/73345622/219948223-f2c60172-ff93-4bdf-b7b7-ff016ee39877.png)

### FMCL logs
无

### Other launcher's launch script
无

**Comment by AGJ-smart** [comment]
我不会自己修（池沼

**Comment by mc-124** [comment]
错误1：update.py发送请求时404
错误2：找不到目录`.minecraft\versions`

**Comment by AGJ-smart** [comment]
> 错误1：update.py发送请求时404 错误2：找不到目录`.minecraft\versions`

请在反馈bug时创建issue，而不是在已存在的issue下提交comment

另外，请附上错误日志或报错信息等信息，方便开发者定位bug并修复。 _可根据新建issue时提供的"Bug Report"模板提供信息。_

感谢支持

**Comment by mc-124** [comment]
> > 错误1：update.py发送请求时404 错误2：找不到目录`.minecraft\versions`
> 
> 请在反馈bug时创建issue，而不是在已存在的issue下提交comment
> 
> 另外，请附上错误日志或报错信息等信息，方便开发者定位bug并修复。 _可根据新建issue时提供的"Bug Report"模板提供信息。_
> 
> 感谢支持

不是，我只是解释你这个bug，你当我交bug的？

**Comment by AGJ-smart** [comment]
> > > 错误1：update.py发送请求时404 错误2：找不到目录`.minecraft\versions`
> > 
> > 
> > 请在反馈bug时创建issue，而不是在已存在的issue下提交comment
> > 另外，请附上错误日志或报错信息等信息，方便开发者定位bug并修复。 _可根据新建issue时提供的"Bug Report"模板提供信息。_
> > 感谢支持
> 
> 不是，我只是解释你这个bug，你当我交bug的？

还真是 对不起我理解错了

**Comment by Sharll-large** [comment]
update暂时停用，第二个问题在重构时解决
